version: '3'

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - my_custom_network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my_custom_network
    healthcheck:
      test: [ "CMD", "nc", "-z", "kafka", "9092" ]  # Check internal listener
      interval: 10s
      timeout: 10s
      retries: 5

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - my_custom_network

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - my_custom_network

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge